version: '3'
services:
    mongodb:
        image: mongo:3.2.6
        ports:
            - "27017:27017"
    mongo_import:
        image: mongo:3.2.6
        links:
            - mongodb
        volumes:
            - ./code:/code
        command:
            sh /code/import.sh
